// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwkypwxociocnwgpcsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod2t5cHd4b2Npb2Nud2dwY3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODEwODQsImV4cCI6MjA2ODg1NzA4NH0.cKlrk74O8l5wTLj9IzB4Hhb0iPkIDn-wV6NMJbWh55A";



export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: {
        getItem: (key) => localStorage.getItem(key),
        setItem: (key, value) => localStorage.setItem(key, value),
        removeItem: (key) => localStorage.removeItem(key),
      },
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
